### ISSUE TITLE
line break in german client

### ISSUE THREAD

**Issue by lescheib** [Microsoft/adfsWebCustomization#10]
Here is an example of a German client with Firefox.

![image](https://user-images.githubusercontent.com/10263247/33482487-909c39e0-d699-11e7-923b-a6d5c4a598db.png)

Can you include the line break in one of your next versions?

**Comment by bongiovimatthew-microsoft** [comment]
Thanks @lescheib. We have a fix for this in review now, and should hopefully get it out soon.
