### ISSUE TITLE
No password field

### ISSUE THREAD

**Issue by benoithamet** [Microsoft/adfsWebCustomization#11]
Hi there
good one to propose that
however seems there is an issue - there is no password field (attached screenshot)
not sure if this is because of the ADFS version (v4) of because the additional auth methods (Azure MFA and Certificate) are enabled
no modification done on your original files
![untitled](https://user-images.githubusercontent.com/15656722/33789077-435ef4c4-dcca-11e7-9325-a082270fe54c.png)

thanks

**Comment by bongiovimatthew-microsoft** [comment]
@benoithamet, thanks for catching this. Would it be possible to get a little more information from you on the issue? 

If possible, could you attach: 

1. The full webpage response that gets returned (you can get this by going to 'view page source' in your browser). 
2. Any errors you see in the developer console in your browser (most browsers open the console console on [F-12])

**Comment by benoithamet** [comment]
no, no error
attached fiddler trace and source
[source.txt](https://github.com/Microsoft/adfsWebCustomization/files/1544139/source.txt)

**Comment by bongiovimatthew-microsoft** [comment]
I don't see anything immediately broken in the source you sent.

Would you mind deploying the debug JavaScript from the debug branch: https://github.com/Microsoft/adfsWebCustomization/blob/debugJavaScript/centeredUi/paginatedOnload.js 

If you run this with the browser console open, and set to keep logs between navigation, then we should hopefully know more. 

Thanks again for reporting this issue!

**Comment by bongiovimatthew-microsoft** [comment]
@benoithamet, thanks again for bringing this issue up. It's possible this issue will be fixed by the same "startsWith" function definition that was just pulled to master. Would you mind re-deploying with the new code and see if that fixes the issue?

**Comment by benoithamet** [comment]
Hi Matthew
I tried again with the latest version of the files (but without the startswith fix) and I got the password field now
However still one last little thing; if you have configured and enable the certificate auth, the display is a little bit messed up (see screenshot)
![untitled](https://user-images.githubusercontent.com/15656722/34635839-3d65fc24-f28d-11e7-9bd6-b0cd8e40495b.png)

**Comment by bongiovimatthew-microsoft** [comment]
Thanks for the feedback. We have a fix for this pending. Would you mind deploying both the CSS and JavaScript from this branch and see if it fixes the issue: https://github.com/Microsoft/adfsWebCustomization/tree/addStartsWith/centeredUi

**Comment by benoithamet** [comment]
Sorry matt; still have the same with the last update

**Comment by anorstrom** [comment]
Hi all,
I have a similar issue, but only in IE. When using IE, the Next Button does not show up under the login name box, so I cannot get to the password box either.  
In Chrome and Edge it works fine.
I downloaded the latest from the Master Branch today.

Kind Regards,
Andreas

**Comment by bongiovimatthew-microsoft** [comment]
Andreas, we just merged another update to master. Would you mind trying that and see if it resolves the issue?

**Comment by anorstrom** [comment]
Thanks a lot Matt!
That update works fine. Now IE looks good too, and when certificate authentication is enabled the link is displayed correctly.

**Comment by benoithamet** [comment]
Thanks
All good on my side too
