### ISSUE TITLE
Darken background to match Azure AD

### ISSUE THREAD

**Issue by bongiovimatthew-microsoft** [Microsoft/adfsWebCustomization#20]
The background on the Azure AD page presents a slightly darkened image, while the current AD FS customization presents the image as-is. 

A side-by-side comparison: 
![image](https://user-images.githubusercontent.com/24795311/35933786-7deddec0-0bf0-11e8-86c6-ff238be90881.png)

**Comment by Ddog800** [comment]
Just submitted a pull requests that implements this.

**Comment by bongiovimatthew-microsoft** [comment]
@Ddog800, thanks again for this fix
