### ISSUE TITLE
Issues customizing "Sign in with your organizational account"

### ISSUE THREAD

**Issue by dsolodow** [Microsoft/adfsWebCustomization#29]
According to https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/advanced-customization-of-ad-fs-sign-in-pages the "Sign in with your organizational account" can be changed in the onload.js

However, I'm not having much luck with it and I'm not familiar enough with javascript to be sure I'm looking in the right place of paginatedOnload.js

Where should I put the replacement string for "Sign in with your organizational account" in the .js file?

**Comment by bongiovimatthew-microsoft** [comment]
@dsolodow, just to clarify, do you want the paginated UI experience, and also to replace the message "Sign in with your organizational account", or do you just need to change the message? Below are the answers for each: 

 __Just Want to Change "Sign in with your organizational account"__ - if you don't care about the paginated UI, you can create a new onload.js file, and include only the code from the help document you linked. 

    // Sample code to change “Sign in with organizational account” string.  
    // Check whether the loginMessage element is present on this page.  
    var loginMessage = document.getElementById('loginMessage');  
    if (loginMessage)  
    {  
           // loginMessage element is present, modify its properties.  
           loginMessage.innerHTML = 'Your company description text';  
    }


__I Want the Paginated UI and to Change The Message__ - in this case, the best place to add the code above is line [766 of paginatedOnload.js](https://github.com/Microsoft/adfsWebCustomization/blob/master/centeredUi/paginatedOnload.js#L766), where the existing code looks like this, with some additions in __bold__: 

    var loginMessage = document.getElementById('loginMessage');
    var originalLoginMessage = "";
    var didLoadPasswordPageBefore = false;

    if ( loginMessage )
    {
            __loginMessage.innerHTML = 'Your company description text';__ 
            originalLoginMessage = loginMessage.innerHTML;
    }
    var didAddListener = false;

An important thing to consider is that we currently have the function [`GetLocalizedStringForElement()`](https://github.com/Microsoft/adfsWebCustomization/blob/master/centeredUi/paginatedOnload.js#L43), which will change the login message to read "Enter Password" when you navigate to the page that asks for the user's password. If you do not want the message to change, you will have to adjust the call to `GetLocalizedStringForElement`. 

Also, the message you set will not be localized by default (meaning it will only show up in the language you set it to), so if your company needs a multi-language message, you will have to add logic to support that.

**Comment by dsolodow** [comment]
I wanted to change the message on the Paginated UI (should have said so initially).

And it also turned out I had a type in my PowerShell for setting the adfs theme and it wasn't applying the paginatedOnload.js to the theme in the first place. 🤦‍♂️
