### ISSUE TITLE
updatepassword page not centered

### ISSUE THREAD

**Issue by 0acff4be45** [Microsoft/adfsWebCustomization#6]
It appears the boxes that show: old password, new password, confirm are out by a few pixels.

![2017-11-28_10-25-58](https://user-images.githubusercontent.com/30828111/33314800-9cee92c6-d426-11e7-9202-606f1ba3e508.png)

**Comment by bongiovimatthew-microsoft** [comment]
Thanks for catching this! We have a fix in review now.
